### LOGIN FORM STUFF
LOGINForm = Window(mainApp, width=449, height=231, title=mainApp.title)
LOGINForm.tk.resizable(False, False)
LOGINtopBox = Box(LOGINForm, width="fill", height=60)
LOGINtitlebox = Box(LOGINtopBox, width="fill", height=33)
LOGINsubtitleBox = Box(LOGINtopBox, width="fill", height=21)
LOGINtitleText = Text(LOGINtitlebox, text="ZOO BOOKING APP", width="fill", height=1, align="bottom")
LOGINtitleText.tk.config(font=('Calibri',30,'bold'))
LOGINsubtitleText = Text(LOGINsubtitleBox, text="LOGIN OR SIGNUP", width="fill", height=1, align="top", size=17)
LOGINsubtitleText.tk.config(font=('Calibri',17,'bold'))
LOGINmiddleBox = Box(LOGINForm, width="fill", height="fill")
LOGINerrorText = Text(LOGINmiddleBox, width="fill", height=1, align="top", text="", size=9, font="Calibri", color="red")
Box(LOGINmiddleBox, width="fill", height=10)
LOGINusernameBox = TextBox(LOGINmiddleBox, text=PLACEHOLDERrusername, width=42)
LOGINusernameBox.tk.config(font=('Calibri', 14, "italic"))
Box(LOGINmiddleBox, width="fill", height=10)
LOGINpasswordBox = TextBox(LOGINmiddleBox, text=PLACEHOLDERpassword, width=42)
LOGINpasswordBox.tk.config(font=('Calibri', 14, "italic"))
LOGINforgotpasswordBox = Box(LOGINmiddleBox, width=429, height=15)
LOGINforgotpassword = Text(LOGINforgotpasswordBox, text="FORGOT PASSWORD", size=8, align="left", color="Blue", font='Calibri')
LOGINforgotpasswordHoverCheck = True
LOGINbottomBox = Box(LOGINForm, width="fill", height=87)
Box(LOGINbottomBox, width=10, height=10, align="left")
Box(LOGINbottomBox, width=10, height=10, align="right")
LOGINbottombuttonsBoxL = Box(LOGINbottomBox, width=155, height="fill", align="left")
LOGINbottombuttonsBoxR = Box(LOGINbottomBox, width=155, height="fill", align="right")
Box(LOGINbottombuttonsBoxL, width="fill", height=10, align="top")
Box(LOGINbottombuttonsBoxR, width="fill", height=10, align="top")
Box(LOGINbottombuttonsBoxL, width="fill", height=10, align="bottom")
Box(LOGINbottombuttonsBoxR, width="fill", height=10, align="bottom")
LOGINloginbutton = PushButton(LOGINbottombuttonsBoxL, text="LOGIN", width=18, command=login)
LOGINloginbutton.bg = "light grey"
LOGINgotosignupbutton = PushButton(LOGINbottombuttonsBoxR, text="GO TO SIGNUP", width=18, command=lambda: showOnly([SIGNUPForm], [LOGINForm, SIGNUPerrorText]))
LOGINgotosignupbutton.bg = "light grey"
LOGINlogo = Picture(LOGINbottomBox, image="LOGO.png")
LOGINforgotpassword.when_mouse_enters = lambda: LOGINforgotpassword.tk.config(font=('Calibri', 8, "underline"))
LOGINforgotpassword.when_mouse_leaves = lambda: LOGINforgotpassword.tk.config(font=('Calibri', 8))
LOGINforgotpassword.tk.config(cursor="hand2")
LOGINloginbutton.tk.config(cursor="hand2")
LOGINgotosignupbutton.tk.config(cursor="hand2")
LOGINusernameBox.text_color = "dark grey"
LOGINpasswordBox.text_color = "dark grey"
LOGINusernameBox.tk.bind("<FocusIn>", lambda type: placeholdertextbox(LOGINusernameBox, str(type), PLACEHOLDERrusername, False))
LOGINusernameBox.tk.bind("<FocusOut>", lambda type: placeholdertextbox(LOGINusernameBox, str(type), PLACEHOLDERrusername, False))
LOGINpasswordBox.tk.bind("<FocusIn>", lambda type: placeholdertextbox(LOGINpasswordBox, str(type), PLACEHOLDERpassword, True))
LOGINpasswordBox.tk.bind("<FocusOut>", lambda type: placeholdertextbox(LOGINpasswordBox, str(type), PLACEHOLDERpassword, True))

SIGNUPacceptcookiesBox.when_mouse_enters = lambda: SIGNUPacceptcookiesBox.tk.config(font=('Calibri', 10, "underline"))
SIGNUPacceptcookiesBox.when_mouse_leaves = lambda: SIGNUPacceptcookiesBox.tk.config(font=('Calibri', 10))
SIGNUPaccepttermsserviceBox.when_mouse_enters = lambda: SIGNUPaccepttermsserviceBox.tk.config(font=('Calibri', 10, "underline"))
SIGNUPaccepttermsserviceBox.when_mouse_leaves = lambda: SIGNUPaccepttermsserviceBox.tk.config(font=('Calibri', 10))
